### ISSUE TITLE
Add a prompt to view release notes on update

### ISSUE THREAD

**Issue by OrsellGaming** [Portal-2-Multiplayer-Mod/Portal2-Multiplayer-Mod#70]
@cabiste69 thought of the idea of adding a change log prompt after a launcher update to show the user what has changed in the update.

**Comment by cabiste69** [comment]
well this is very easy to do, we can use Tk for the prompt but the issue is the UI design (i suck at UI design)

**Comment by OrsellGaming** [comment]
This was a accident didn't mean to create it. But ill keep that in mind.

**Comment by OrsellGaming** [comment]
@cabiste69 moved to issue #71, that way its linked to the todo list.
